<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class PermissionRoleTableSeeder extends Seeder
{
    public function run()
    {
        $admin_permissions = Permission::all();
        Role::findOrFail(1)->permissions()->sync($admin_permissions->pluck('id'));
        $manager_permissions = $admin_permissions->filter(function ($permission) {
            return substr($permission->title, 0, 5) != 'user_' && substr($permission->title, 0, 5) != 'role_' && substr($permission->title, 0, 11) != 'permission_' && substr($permission->title, 0, 5) != 'team_' && substr($permission->title, 0, 6) != 'audit_';
        });
        Role::findOrFail(2)->permissions()->sync($manager_permissions);
        $warehouse_permissions = $admin_permissions->filter(function ($permission) {
            return substr($permission->title, 0, 5) != 'user_' && substr($permission->title, 0, 5) != 'role_' && substr($permission->title, 0, 11) != 'permission_' && substr($permission->title, 0, 5) != 'team_' && substr($permission->title, 0, 4) != 'crm_' && substr($permission->title, 0, 6) != 'audit_' && substr($permission->title, 0, 5) != 'task_'  && substr($permission->title, 0, 5) != 'time_' && substr($permission->title, 0, 4) != 'faq_' && substr($permission->title, 0, 9) != 'products_' && substr($permission->title, 0, 5) != 'time_' && substr($permission->title, 0, 22) != 'warehouses_list_delete' && substr($permission->title, 0, 17) != 'receipt_note_edit' && substr($permission->title, 0, 19) != 'receipt_note_delete' && substr($permission->title, 0, 18) != 'delivery_note_edit' && substr($permission->title, 0, 20) != 'delivery_note_delete' && substr($permission->title, 0, 25) != 'warehouse_transfer_delete' && substr($permission->title, 0, 23) != 'warehouse_transfer_edit' && substr($permission->title, 0, 19) != 'packing_list_delete' && substr($permission->title, 0, 17) != 'packing_list_edit' && substr($permission->title, 0, 19) != 'packing_list_delete' && substr($permission->title, 0, 4) != 'pdf_' && substr($permission->title, 0, 4) != 'lot_' && substr($permission->title, 0, 11) != 'processing_' && substr($permission->title, 0, 8) != 'BasicCRM'  && substr($permission->title, 0, 8) != 'half_'  && substr($permission->title, 0, 7) != 'oldest_' && substr($permission->title, 0, 8) != 'product_'  && substr($permission->title, 0, 15) != 'product_balance'  && substr($permission->title, 0, 14) != 'bill_material_' && substr($permission->title, 0, 11) != 'production_' && substr($permission->title, 0, 16) != 'create_finished_' && substr($permission->title, 0, 16) != 'production_spent' && substr($permission->title, 0, 16) != 'product_balance_' && substr($permission->title, 0, 14) != 'product_price_' && substr($permission->title, 0, 8) != 'expense_' && substr($permission->title, 0, 7) != 'income_' && substr($permission->title, 0, 18) != 'basic_c_r_m_access';
        });
        Role::FindOrFail(3)->permissions()->sync($warehouse_permissions);
        $processing_permissions = $manager_permissions->filter(function ($permission) {
            return substr($permission->title, 0, 5) != 'user_' && substr($permission->title, 0, 5) != 'role_' && substr($permission->title, 0, 11) != 'permission_' && substr($permission->title, 0, 5) != 'team_' && substr($permission->title, 0, 4) != 'crm_' && substr($permission->title, 0, 6) != 'audit_' && substr($permission->title, 0, 5) != 'task_'  && substr($permission->title, 0, 5) != 'time_' && substr($permission->title, 0, 4) != 'faq_' && substr($permission->title, 0, 9) != 'products_' && substr($permission->title, 0, 5) != 'time_' && substr($permission->title, 0, 22) != 'warehouses_list_delete' && substr($permission->title, 0, 17) != 'receipt_note_edit' && substr($permission->title, 0, 19) != 'receipt_note_delete' && substr($permission->title, 0, 18) != 'delivery_note_edit' && substr($permission->title, 0, 20) != 'delivery_note_delete' && substr($permission->title, 0, 25) != 'warehouse_transfer_delete' && substr($permission->title, 0, 23) != 'warehouse_transfer_edit' && substr($permission->title, 0, 17) != 'packing_list_edit' && substr($permission->title, 0, 19) != 'packing_list_delete' && substr($permission->title, 0, 4) != 'pdf_' && substr($permission->title, 0, 4) != 'lot_' && substr($permission->title, 0, 7) != 'oldest_' && substr($permission->title, 0, 8) != 'product_'  && substr($permission->title, 0, 15) != 'product_balance'  && substr($permission->title, 0, 14) != 'bill_material_' && substr($permission->title, 0, 16) != 'product_balance_' && substr($permission->title, 0, 14) != 'product_price_' && substr($permission->title, 0, 8) != 'expense_' && substr($permission->title, 0, 7) != 'income_' && substr($permission->title, 0, 18) != 'basic_c_r_m_access' && substr($permission->title, 0, 11) != 'warehouses_' && substr($permission->title, 0, 8) != 'receipt_' && substr($permission->title, 0, 9) != 'delivery_' && substr($permission->title, 0, 9) != 'delivery_' && substr($permission->title, 0, 10) != 'warehouse_' && substr($permission->title, 0, 6) != 'asset_';
        });
        Role::FindOrFail(4)->permissions()->sync($processing_permissions);
        $sales_permissions = $manager_permissions->filter(function ($permission) {
            return substr($permission->title, 0, 5) != 'user_' && substr($permission->title, 0, 5) != 'role_' && substr($permission->title, 0, 11) != 'processing_' && substr($permission->title, 0, 11) != 'permission_' && substr($permission->title, 0, 5) != 'team_' && substr($permission->title, 0, 4) != 'crm_' && substr($permission->title, 0, 6) != 'audit_' && substr($permission->title, 0, 5) != 'time_' && substr($permission->title, 0, 4) != 'faq_' && substr($permission->title, 0, 9) != 'products_' && substr($permission->title, 0, 5) != 'time_' && substr($permission->title, 0, 22) != 'warehouses_list_delete' && substr($permission->title, 0, 17) != 'receipt_note_edit' && substr($permission->title, 0, 19) != 'receipt_note_delete' && substr($permission->title, 0, 18) != 'delivery_note_edit' && substr($permission->title, 0, 20) != 'delivery_note_delete' && substr($permission->title, 0, 25) != 'warehouse_transfer_delete' && substr($permission->title, 0, 23) != 'warehouse_transfer_edit' && substr($permission->title, 0, 17) != 'packing_list_edit' && substr($permission->title, 0, 19) != 'packing_list_delete' && substr($permission->title, 0, 4) != 'pdf_' && substr($permission->title, 0, 4) != 'lot_' && substr($permission->title, 0, 7) != 'oldest_' && substr($permission->title, 0, 14) != 'product_access'  && substr($permission->title, 0, 14) != 'bill_material_' && substr($permission->title, 0, 16) != 'product_balance_' && substr($permission->title, 0, 8) != 'expense_' && substr($permission->title, 0, 7) != 'income_' && substr($permission->title, 0, 11) != 'warehouses_' && substr($permission->title, 0, 8) != 'receipt_' && substr($permission->title, 0, 9) != 'delivery_' && substr($permission->title, 0, 9) != 'delivery_' && substr($permission->title, 0, 10) != 'warehouse_' && substr($permission->title, 0, 18) != 'basic_c_r_m_access' && substr($permission->title, 0, 6) != 'asset_' && substr($permission->title, 0, 18) != 'task_status_access' && substr($permission->title, 0, 9) != 'task_tag_' && substr($permission->title, 0, 12) != 'task_status_' && substr($permission->title, 0, 11) != 'task_access' && substr($permission->title, 0, 7) != 'assets_' && substr($permission->title, 0, 8) != 'packing_' && substr($permission->title, 0, 5) != 'note_' && substr($permission->title, 0, 5) != 'half_' && substr($permission->title, 0, 7) != 'create_';
        });
        Role::FindOrFail(5)->permissions()->sync($sales_permissions);
    }
}
